# Generated by Django 2.2.4 on 2019-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_suser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='password',
            field=models.CharField(max_length=120, verbose_name='비밀번호'),
        ),
    ]
